-- admin / admin
INSERT INTO USERS (USR_ID, USR_LOGIN, USR_EMAIL, USR_PASSWORD, USR_NAME, USR_TYPE, USR_ACTIVE) VALUES (NEXTVAL('SEQ_USR'), 'admin', 'admin@admin', '$2a$10$vmcVvka4ry36WUgPj8nNLOpGf5K7YZ9fX80y9Pfh7CFkuEH/sbh.W', 'Admin Admin', 'ADMIN', TRUE);
-- user / user
INSERT INTO USERS (USR_ID, USR_LOGIN, USR_EMAIL, USR_PASSWORD, USR_NAME, USR_TYPE, USR_ACTIVE) VALUES (NEXTVAL('SEQ_USR'), 'user', 'user@user', '$2a$10$AefgN0Ks8bjOFIHVL2mt1uDwz/MPd3egPB9DtQLFpIS9jMjChqXPq', 'User User', 'USER', TRUE);